# Database
spring.datasource.url=jdbc:mysql://localhost:3306/smart_blood_bank
spring.datasource.username=root
spring.datasource.password=@Amar6733
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# App name
spring.application.name=smart-blood-bank
server.port=8080